export const TOPICS = {
 nombor:['Nombor & operasi','＋'], pecahan:['Pecahan & perpuluhan','½'], wang:['Wang','RM'], masa:['Masa & waktu','◷'], ukuran:['Ukuran & sukatan','↔'], ruang:['Ruang','△'], data:['Pengurusan data','▥'], koordinat:['Koordinat & nisbah','⌖']
};
export const LIMITS=[0,100,1000,10000,100000,1000000,10000000];
export function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function shuffle(a,r=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const fmt=n=>Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000);
export const BANK=[];
const seen=new Set();
function add(y,topic,skill,type,text,answer,explanation,unit='',visual='',choices){const key=y+'|'+text+'|'+visual;if(seen.has(key))return;seen.add(key);BANK.push({id:'MM-'+String(BANK.length+1).padStart(5,'0'),year:y,topic,skill,type,text,answer:fmt(answer),explanation,unit,visual,choices,level:type==='berayat'?'Aplikasi':'Asas'});}
const names=['Aina','Ravi','Mei Ling','Haziq','Siti','Daniel','Irfan','Devi'];
const r=rng(20260915),int=(a,b)=>Math.floor(r()*(b-a+1))+a;
const shapeSvg=(kind,a,b)=>`<svg viewBox="0 0 200 130" role="img" aria-label="${kind}">${kind==='Segi tiga'?'<path d="M100 15 L175 105 H25Z"/>':'<rect x="35" y="20" width="130" height="80"/>'}<style>path,rect{fill:#dce9c4;stroke:#528465;stroke-width:3}</style><text x="100" y="123" text-anchor="middle" font-size="13">${a ? a+" cm" : ""}</text>${b?`<text x="170" y="60" font-size="13">${b} cm</text>`:''}</svg>`;
for(let y=1;y<=6;y++){
 for(let i=0;i<50;i++){
  const max=LIMITS[y],a=int(5,Math.floor(max*.55)),b=int(2,Math.floor(max*.35)),n=names[i%names.length];
  add(y,'nombor','Tambah','kiraan',`${a} + ${b} = ?`,a+b,`Tambahkan kedua-dua nombor: ${a} + ${b} = ${a+b}.`);
  add(y,'nombor','Tolak','berayat',`${n} mempunyai ${a+b} keping pelekat. Sebanyak ${b} keping diberikan kepada rakannya. Berapakah baki pelekat ${n}?`,a,`Baki = jumlah asal − yang diberi = ${a+b} − ${b} = ${a}.`,'keping');
  const step=y===1?int(1,5):10**(y-1),start=int(1,Math.floor(max/step)-3)*step;
  add(y,'nombor','Pola nombor','kiraan',`Lengkapkan pola: ${start}, ${start+step}, ${start+2*step}, __.`,start+3*step,`Pola bertambah ${step}. ${start+2*step} + ${step} = ${start+3*step}.`);
  const place=10**int(0,y===1?1:y-1),digit=Math.floor(a/place)%10;
  add(y,'nombor','Nilai tempat','kiraan',`Dalam nombor ${a}, apakah nilai digit pada tempat ${['sa','puluh','ratus','ribu','puluh ribu','ratus ribu'][Math.log10(place)]}?`,digit*place,`Digit ${digit} bernilai ${digit} × ${place} = ${digit*place}.`);
  if(y>=2){const m=y===2?[2,5,10][i%3]:int(2,y>=4?20:9),k=int(2,y===2?10:Math.floor(max/m/2));add(y,'nombor','Darab','berayat',`Sebuah kotak mengandungi ${k} batang pensel. Cikgu membeli ${m} kotak yang sama. Berapakah jumlah pensel?`,m*k,`Jumlah = ${m} × ${k} = ${m*k}.`,'batang');add(y,'nombor','Bahagi','kiraan',`${m*k} ÷ ${m} = ?`,k,`${m} × ${k} = ${m*k}, maka ${m*k} ÷ ${m} = ${k}.`);}
  if(y>=3){const c=int(1,b);add(y,'nombor','Operasi bergabung','berayat',`Perpustakaan mempunyai ${a} buah buku. Sebanyak ${b} buku baharu diterima, kemudian ${c} buku dipinjam. Berapakah buku yang tinggal?`,a+b-c,`Jumlah baharu = ${a} + ${b} = ${a+b}. Baki = ${a+b} − ${c} = ${a+b-c}.`,'buah');}
  // Money uses integer sen internally; Year 1 stays within RM10.
  const cost=int(1,y===1?8:y===2?60:y===3?300:2000),paid=cost+int(1,y===1?10-cost:50);
  add(y,'wang','Baki wang','berayat',`${n} membeli sebuah buku berharga RM${cost}. Dia membayar RM${paid}. Berapakah baki wangnya?`,paid-cost,`Baki = RM${paid} − RM${cost} = RM${paid-cost}.`,'RM');
  if(y>=2){const sen=int(1,9)*10;add(y,'wang','Ringgit dan sen','kiraan',`Tukarkan RM${cost}.${sen} kepada sen.`,cost*100+sen,`RM1 = 100 sen. (${cost} × 100) + ${sen} = ${cost*100+sen} sen.`,'sen');}
  if(y>=4){const k=int(2,8);add(y,'wang','Jumlah harga','berayat',`${n} membeli ${k} pek alat tulis dengan harga RM${cost} sepeket. Berapakah jumlah bayaran?`,cost*k,`Jumlah harga = ${k} × RM${cost} = RM${cost*k}.`,'RM');}
  if(y>=5){const pct=[10,20,25,50][i%4],price=int(2,30)*20;add(y,'wang','Diskaun','berayat',`Harga sebuah beg ialah RM${price}. Kedai memberikan diskaun ${pct}%. Berapakah harga selepas diskaun?`,price*(100-pct)/100,`Diskaun = ${pct}/100 × RM${price} = RM${price*pct/100}. Harga akhir = RM${price} − RM${price*pct/100} = RM${price*(100-pct)/100}.`,'RM');}
  if(y===6){const cost2=int(20,300),profit=int(5,60);add(y,'wang','Untung dan rugi','berayat',`Harga kos sebuah hamper ialah RM${cost2}. Hamper itu dijual pada harga RM${cost2+profit}. Hitung keuntungan yang diperoleh.`,profit,`Untung = harga jual − harga kos = RM${cost2+profit} − RM${cost2} = RM${profit}.`,'RM');}
  const h=int(1,10),dur=int(1,3);
  if(y===1){add(y,'masa','Waktu dalam jam','berayat',`Pada waktu pagi, jarum pendek jam menunjuk ${h} dan jarum panjang menunjuk 12. Pukul berapakah itu?`,h,`Jarum panjang di 12 menunjukkan tepat jam. Jarum pendek di ${h}: pukul ${h} pagi.`,'pagi');}
  else if(y===6){const diff=int(1,8);add(y,'masa','Zon masa','berayat',`Waktu di bandar A ialah pukul ${h}:00 pagi. Bandar B adalah ${diff} jam lebih awal daripada bandar A. Nyatakan waktu di bandar B dalam sistem 24 jam (jam sahaja).`,h+diff,`Bandar B mendahului bandar A. ${h} + ${diff} = ${h+diff}, iaitu ${String(h+diff).padStart(2,'0')}:00.`,'jam');}
  else{const mins=[15,30,45][i%3];add(y,'masa','Tempoh masa','berayat',`Latihan bermula pada pukul ${h}:00 pagi dan berakhir pada pukul ${h}:${mins} pagi. Berapa minit latihan itu berlangsung?`,mins,`Masa tamat − masa mula = ${mins} − 0 = ${mins} minit.`,'minit');add(y,'masa','Penukaran masa','kiraan',`${dur} jam ${mins} minit = berapa minit?`,dur*60+mins,`1 jam = 60 minit. (${dur} × 60) + ${mins} = ${dur*60+mins}.`,'minit');}
  const len=int(3,40),used=int(1,len-1);
  if(y===1){add(y,'ukuran','Unit bukan piawai','berayat',`Panjang pensel A ialah ${used} klip kertas. Panjang pensel B ialah ${len} klip kertas yang sama saiz. Berapa klip kertas lebih panjang pensel B?`,len-used,`Bezanya ialah ${len} − ${used} = ${len-used} klip kertas.`,'klip');}
  else{add(y,'ukuran','Panjang','berayat',`Seutas reben panjangnya ${len} cm. ${n} memotong ${used} cm daripada reben itu. Berapakah panjang reben yang tinggal?`,len-used,`${len} cm − ${used} cm = ${len-used} cm.`,'cm');const kg=int(1,9),g=int(1,9)*100;add(y,'ukuran','Jisim','kiraan',`${kg} kg ${g} g = berapa gram?`,kg*1000+g,`1 kg = 1000 g. (${kg} × 1000) + ${g} = ${kg*1000+g} g.`,'g');const l=int(2,9),ml=int(1,9)*100;add(y,'ukuran','Isi padu cecair','berayat',`Sebuah jag mengandungi ${l} L air. Sebanyak ${ml} mL air dituang keluar. Berapakah baki air dalam mL?`,l*1000-ml,`${l} L = ${l*1000} mL. Baki = ${l*1000} − ${ml} = ${l*1000-ml} mL.`,'mL');}
  if(y===6){const m=int(2,9),density=int(2,8)*100;add(y,'ukuran','Perkaitan ukuran','berayat',`Jisim setiap meter dawai ialah ${density} g. Berapakah jisim ${m} m dawai yang sama dalam kg?`,m*density/1000,`Jisim = ${m} × ${density} = ${m*density} g. Bahagi 1000 untuk mendapat ${fmt(m*density/1000)} kg.`,'kg');}
  if(y<=2){const shapes=[['Segi tiga',3],['Segi empat sama',4],['Segi empat tepat',4]],s=shapes[i%3];add(y,'ruang','Bentuk dua dimensi','kiraan',`Berapakah bilangan sisi bagi ${s[0].toLowerCase()}?`,s[1],`${s[0]} mempunyai ${s[1]} sisi.`,'sisi',shapeSvg(s[0], '', ''));const solids=[['kubus',6],['kuboid',6],['piramid tapak segi empat sama',5]];const so=solids[i%3];add(y,'ruang','Bentuk tiga dimensi','kiraan',`Berapakah bilangan permukaan rata pada ${so[0]}?`,so[1],`${so[0]} mempunyai ${so[1]} permukaan rata.`,'permukaan');}
  else{const w=int(2,12),l=int(w,20);add(y,'ruang','Luas','berayat',`Sebuah kad berbentuk segi empat tepat mempunyai panjang ${l} cm dan lebar ${w} cm. Hitung luas kad itu.`,l*w,`Luas = panjang × lebar = ${l} × ${w} = ${l*w} cm².`,'cm²',shapeSvg('Segi empat tepat',l,w));add(y,'ruang','Perimeter','kiraan',`Hitung perimeter segi empat tepat berukuran ${l} cm × ${w} cm.`,2*(l+w),`Perimeter = 2 × (panjang + lebar) = 2 × (${l} + ${w}) = ${2*(l+w)} cm.`,'cm',shapeSvg('Segi empat tepat',l,w));}
  if(y>=5){const s=int(2,12);add(y,'ruang','Isi padu','kiraan',`Sebuah kubus mempunyai sisi ${s} cm. Berapakah isi padunya?`,s**3,`Isi padu = sisi × sisi × sisi = ${s} × ${s} × ${s} = ${s**3} cm³.`,'cm³');}
  const v1=int(2,20),v2=int(2,20),v3=int(2,20);const table=`<table class="data-table"><caption>Buku yang dibaca</caption><tr><th>Aina</th><th>Ravi</th><th>Mei Ling</th></tr><tr><td>${v1}</td><td>${v2}</td><td>${v3}</td></tr></table>`;
  add(y,'data','Tafsiran data','berayat',`Jadual menunjukkan bilangan buku yang dibaca oleh tiga orang murid. Berapakah jumlah buku yang dibaca?`,v1+v2+v3,`Jumlah = ${v1} + ${v2} + ${v3} = ${v1+v2+v3}.`,'buah',table);
  if(y>=5){const a2=int(2,15),b2=a2+int(1,5),c2=b2+int(1,5);add(y,'data','Median','kiraan',`Cari median bagi data ${a2}, ${b2}, ${c2}.`,b2,`Data telah disusun menaik. Median ialah nilai tengah, iaitu ${b2}.`);add(y,'data','Min','kiraan',`Cari min bagi data ${a2}, ${a2+3}, ${a2+6}.`,a2+3,`Min = jumlah ÷ bilangan data = ${a2*3+9} ÷ 3 = ${a2+3}.`);}
  if(y>=2){const den=y===2?[2,4][i%2]:int(3,10),num=int(1,den-1),total=den*int(2,9);add(y,'pecahan','Pecahan daripada kuantiti','berayat',`Sebuah kotak mempunyai ${total} biji guli. Sebanyak 1/${den} daripada guli itu berwarna biru. Berapakah bilangan guli biru?`,total/den,`Bahagikan ${total} kepada ${den} bahagian sama: ${total} ÷ ${den} = ${total/den}.`,'biji');if(y>=3){add(y,'pecahan','Pecahan wajar','kiraan',`${num}/${den} daripada ${total} = ?`,total*num/den,`${total} ÷ ${den} × ${num} = ${total*num/den}.`);const d1=int(1,90),d2=int(1,90);add(y,'pecahan','Perpuluhan','kiraan',`${fmt(d1/10)} + ${fmt(d2/10)} = ?`,(d1+d2)/10,`Selaraskan titik perpuluhan. ${fmt(d1/10)} + ${fmt(d2/10)} = ${fmt((d1+d2)/10)}.`);}}
  if(y>=4){const percent=[10,20,25,50,75][i%5],qty=int(1,15)*20;add(y,'pecahan','Peratus','berayat',`Terdapat ${qty} orang murid. Sebanyak ${percent}% menyertai kelab catur. Berapakah murid yang menyertai kelab catur?`,qty*percent/100,`${percent}% × ${qty} = ${percent}/100 × ${qty} = ${qty*percent/100}.`,'orang');}
  if(y>=4){const x=int(1,8),z=int(1,8);add(y,'koordinat','Koordinat','kiraan',`Titik P berada pada koordinat (${x}, ${z}). Apakah nilai koordinat mengufuk (paksi-x) bagi P?`,x,`Koordinat ditulis (x, y). Nilai pertama ialah ${x}.`);}
  if(y>=5){const ratio=int(2,8),unit=int(2,15);add(y,'koordinat','Nisbah','berayat',`Nisbah bilangan buku Aina kepada Ravi ialah 1 : ${ratio}. Aina mempunyai ${unit} buah buku. Berapakah buku Ravi?`,ratio*unit,`1 bahagian = ${unit} buah. ${ratio} bahagian = ${ratio} × ${unit} = ${ratio*unit}.`,'buah');}
  if(y===6){const x=int(1,5),d=int(1,5),scale=int(2,6);add(y,'koordinat','Jarak mengikut skala','berayat',`Pada peta, A berada di (${x}, 2) dan B di (${x+d}, 2). Setiap unit mewakili ${scale} km. Berapakah jarak AB?`,d*scale,`Jarak mengufuk = ${x+d} − ${x} = ${d} unit. Jarak sebenar = ${d} × ${scale} = ${d*scale} km.`,'km');}
 }
}
export function options(q,r=Math.random){if(q.choices)return shuffle(q.choices,r);const val=Number(q.answer),step=Number.isInteger(val)?1:.1;const set=new Set([q.answer]);for(const d of [step,-step,step*2,step*3,step*10]){if(val+d>=0)set.add(fmt(val+d));if(set.size===4)break;}return shuffle([...set],r);}
export function checkAnswer(input,answer){let s=String(input).trim().replace(/^RM\s*/i,'').replace(/\s/g,'');if(/^\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replaceAll(',','');if(!/^-?\d+(\.\d+)?$/.test(s))return false;return Math.abs(Number(s)-Number(answer))<1e-8;}
